 <!DOCTYPE html>
  <html>
    <head>
      <!--Import materialize.css-->
      <link type="text/css" rel="stylesheet" href="css/materialize.min.css"  media="screen,projection"/>
      <link type="text/css" rel="stylesheet" href="css/style.css"  media="screen,projection"/>

      <!--Let browser know website is optimized for mobile-->
      <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
    </head>

    <body>
    	<div id="intro" class="z-depth-2 blue darken-4 white-text center">
	        <h1>GoSMS Backup Reader</h1>
		</div>

<?php
#Init
$bForm = false;
$aMessages = null;

if(isset($_FILES['userfile'])){

	#Including our class.
	require_once 'class/xmlClass.php';

	#Upload code from PHP docs.
	$uploaddir = __DIR__.'/uploads/';
	$uploadfile = $uploaddir . basename($_FILES['userfile']['name']);

	if (move_uploaded_file($_FILES['userfile']['tmp_name'], $uploadfile)) {
	    $XML = new xmlClass($uploadfile);

	    $aMessages = $XML->showTime();
	    $bForm = true; //A flag to know if the form has been sent and all good.
	}

	#We always delete the uploaded file
    unlink($uploadfile);
}
?>
		<div class="container">
<?php
if($bForm){
?>
<ul class="collapsible" data-collapsible="accordion">
<?php 
//Show each conversations
foreach ($aMessages as $auteur => $aConversation) {
	$iNb = sizeof($aConversation);
	echo '<li>
      <div class="collapsible-header">'.$auteur.' ('.$iNb.' messages)</div>
      <div class="collapsible-body"><div class="row">';
    
    //Show messages of this specific conversation
    foreach ($aConversation as $aSMS) {
    	if($aSMS['type'] == 'received'){
    		echo '<div class="col s12">
		      	<div class="row">
		      	        <div class="col s12 m6">
		      	          <div class="card teal lighten-4">
		      	            <div class="card-content white-text">
		      	          		<p>'.$aSMS['content'].'</p>
		      	            </div>
		      	            <div class="card-action">
		      	            	<p>'.$aSMS['date'].'</p>
		      	            </div>
		      	          </div>
		      	        </div>
		      	      </div>
	      	</div>';
    	} else {
    		echo '<div class="col s12">
		      	<div class="row">
		      	        <div class="col s12 m6">
		      	          <div class="card-panel cyan lighten-2">
		      	            	<p>'.$aSMS['content'].'</p>
		      	            	<p>'.$aSMS['date'].'</p>
		      	          </div>
		      	        </div>
		      	      </div>
	      	</div>';
    	}
    }

    echo '</div></div></li>';
}
?>
    
    

  </ul>
<?php

}
?>

			<p>Please upload the XML file generated by your GoSMS application :</p>
			<form method="post" enctype="multipart/form-data">
				<div class="file-field input-field">
				    <input class="file-path validate disabled" type="text"/>
				    <div class="btn">
				        <span>XML</span>
				        <input type="file" name="userfile"/>
			      	</div>
			    </div>
			    <div class="right-align">
				    <button class="btn waves-effect waves-light" type="submit" name="action">Submit
				        <i class="mdi-content-send right"></i>
				    </button>
			    </div>
			</form>
		</div>

		<div class="container">
			<div class="row">
		      <div class="col s12">
		        <div class="card-panel red lighten-2 white-text">
		          <div class="row">
		          	<div class="col s1">
			          <i class="medium mdi-alert-warning"></i>
			        </div>
			        <div class="col s10">
			          <p>This application doesn't save any 
			          information. The file you send is immediately deleted
			          afterwards.</p><p>
			          If you want to archive the result of your SMS backup, simply
			          save this webpage through your navigator (Usually : File - Save
			          or Ctrl + S).
			          </p>
			        </div>
		        </div>
		      </div>
		    </div>
	    </div>
      <!--Import jQuery before materialize.js-->
      <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
      <script type="text/javascript" src="js/materialize.min.js"></script>
    </body>
  </html>